import React from 'react';
import Icon1 from '../../images/crypto.svg';
import Icon2 from '../../images/data.svg';
import Icon3 from '../../images/rev.svg';
import Icon4 from '../../images/MakeMoreMoney.svg';
import Icon5 from '../../images/EnhancedCollaboration.svg';
import Icon6 from '../../images/ImprovedBusiness.svg';

import { ServicesContainer,ServicesH1,ServicesWrapper,ServicesCard,ServicesIcon,ServicesH2,ServicesP } from "./ServicesElements";

const Services = () => {
    return (
        <ServicesContainer id="services">
            <ServicesH1 darkTitle>Our Services</ServicesH1>
            <ServicesWrapper>
                <ServicesCard darkBg>
                    <ServicesIcon src={Icon1}/>
                    <ServicesH2>Improve Storing Management</ServicesH2>
                    <ServicesP>incorporates an advanced, finite capacity based, planning.</ServicesP>
                </ServicesCard>
                <ServicesCard darkBg>
                    <ServicesIcon src={Icon2}/>
                    <ServicesH2>Save your assets</ServicesH2>
                    <ServicesP>By decreasing storage costs and tying up cash and working capital.</ServicesP>
                </ServicesCard>
                <ServicesCard darkBg>
                    <ServicesIcon src={Icon3}/>
                    <ServicesH2>Improve your productivity</ServicesH2>
                    <ServicesP>By Using an ERP System To Manage Inventory .</ServicesP>
                </ServicesCard>
                <ServicesCard darkBg>
                    <ServicesIcon src={Icon4}/>
                    <ServicesH2>Make More Money</ServicesH2>
                    <ServicesP>When Improving Storing Management and Productivity You Will Save Money and Make More Money.</ServicesP>
                </ServicesCard>                <ServicesCard darkBg>
                    <ServicesIcon src={Icon5}/>
                    <ServicesH2>Enhanced collaboration</ServicesH2>
                    <ServicesP>from users sharing data in contracts, requisitions, and purchase orders.</ServicesP>
                </ServicesCard>                <ServicesCard darkBg>
                    <ServicesIcon src={Icon6}/>
                    <ServicesH2>Improved business insight</ServicesH2>
                    <ServicesP>by real-time information generated by reports.</ServicesP>
                </ServicesCard>
            </ServicesWrapper>
        </ServicesContainer>
    )
}

export default Services;
